editable_elements:
  texto_principal:
    text:
      "Padre de Familia Desesperado y En Bancarrota<br>Descubre Una Industria Que Lo Transforma en Millonario…"
    css:
      font-size:
        "50px"
    tablet_css:
      font-size:
        "28px"
    phone_css:
      font-size:
        "28px"
  texto_direccion_envio:
    text:
      "[¿Dónde puede enviarte esta información?]"
    css:
      font-size:
        "18px"
    tablet_css:
      font-size:
        "18px"
    phone_css:
      font-size:
        "18px"
  texto_secundario:
    text:
      "¿Cómo Puedes Ser Parte de Esta Industria?"
    css:
      font-size:
        "32px"
    tablet_css:
      font-size:
        "32px"
    phone_css:
      font-size:
        "32px"
  input_send:
    value:
      "Enviar Ahora"
    css:
      font-size:
        "24px"
  input_name:
    placeholder:
      "Ingresa tu nombre"
  input_mail:
    placeholder:
      "Ingresa tu email"
  texto_derechos:
    text:
      "© 2014 - Todos los derechos reservados."
    css:
      font-size:
        "16px"
    tablet_css:
      font-size:
        "16px"
    phone_css:
      font-size:
        "16px"
editable_styles:
  "selector":
    css:
      background-color:
        "#ffffff"
available_fonts:
  "Source Sans Pro": 
    "'Source Sans Pro', sans-serif"
  "Helvetica Neue": 
    "'Helvetica Neue', Helvetica, Arial, sans-serif"
  "Myriad Pro":
    "'Myriad Pro'"
  "Impact":
    "Impact"
  "Oswald":
    "Oswald, sans-serif"
  "Segoe UI":
    "'Segoe UI', Arial, 'Helvetica Neue', Helvetica, sans-serif"
available_font_sizes: 
  ["8px","10px","12px","14px","15px","16px","17px","18px","20px","22px","24px","28px","29px","30px","32px","36px","40px","42px","44px","50px","63px","67px","70px"]
available_images:
  template_images:
    []
  user_images:
    []


scripts:
  head_tracking_script:
    ""

  bottom_tracking_script:
    ""
seo:
  title:
    "Padre de Familia Desesperado y En Bancarrota Descubre Una Industria Que Lo Transforma en Millonario"
  description:
    "page description"
  keywords:
    "keywords"